# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

# This is a shared configuration file that is intended to be stored in the project repo.
# For local overrides:
# - create .docksal/docksal-local.yml file and put local docker-compose configuration overrides there
# - add .docksal/docksal-local.yml to .gitignore

# Docksal stiches several docker-compose configuration files together.
# Run "fin config" to see which files are involved and the resulting configration.

version: "2"

services:
  # Web node
  web:
    hostname: web
    image: docksal/apache:2.2-stable
    volumes:
      # Project root volume
      - project_root:/var/www
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    depends_on:
      - cli

  # DB node
  db:
    hostname: db
    image: docksal/mysql:5.5
    ports:
      - ${MYSQL_PORT}
    volumes:
      # DB data volume
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  # CLI node
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:php7
    volumes:
      # Project root volume
      - project_root:/var/www
      # Host home volume (for SSH keys and other credentials).
      - host_home:/.home:ro
    # Mount shared ssh-agent socket
    volumes_from:
      - container:ssh-agent
